---
all:
  hosts:
    jenkins-master-01:
      ansible_host: 51.250.70.117
    jenkins-agent-01:
      ansible_host: 158.160.57.44
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agents:
          hosts:
              jenkins-agent-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: slava