---
all:
  hosts:
    jenkins-master-01:
      ansible_host: 84.252.131.246
    jenkins-agent-01:
      ansible_host: 51.250.75.7
    jenkins-agent-02:
      ansible_host: 51.250.85.117
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agents:
          hosts:
              jenkins-agent-01:
              jenkins-agent-02:
  vars:
    ansible_connection_type: paramiko
    ansible_user: slava