---
- name: Preapre all hosts
  hosts: all
  tasks:
    - name: Create group
      become: true
      group:
        name: "{{ user_group }}"
        state: present
    - name: Create user
      become: true
      user:
        name: "{{ user_name }}"
        generate_ssh_key: true
      register: ssh_key_info
    - name: Install JDK
      become: true
      package:
        name: "{{ java_packages }}"
        state: present

- name: Get Jenkins master installed
  hosts: jenkins_masters
  tasks:
#    - name: Get repo Jenkins
#      become: true
#      get_url:
#        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
#        dest: /etc/apt/sources.list.d/jenkins.repo
#        validate_certs: false
#    - name: Add Jenkins key
#      become: true
#      apt_key:
#        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
#        keyring: /usr/share/keyrings/jenkins-keyring.asc
#        state: present
#        validate_certs: false
    - name: Add APT key Jenkins
      become: true
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io-2023.key
        state: present
        validate_certs: false
    - name: Ensure repo is configured
      apt_repository:
        state: present
        repo: 'deb https://pkg.jenkins.io/debian-stable binary/'
    - name: Install Jenkins and requirements
      become: true
      apt:
        name:
          - jenkins
          - git
        state: present
      register: jenkins_installed
# add if need check agents
#    - name: Ensure jenkins agents are present in known_hosts file
#      become: true
#      become_user: "{{ jenkins_user_name }}"
#      known_hosts:
#        name: "{{ hostvars[item].ansible_host }}"
#        state: present
#        key: "{{ lookup('pipe', 'ssh-keyscan {{ hostvars[item].ansible_host }}') }}"
#        hash_host: true
#      with_items: "{{ groups.jenkins_agents }}"
#    - name: Start Jenkins
#      become: true
#      systemd:
#        name: jenkins
#        state: restarted
#        enabled: true
#      when: jenkins_installed is changed
#- name: Prepare jenkins agent
#  hosts: jenkins_agents
#  become: true
#  become_user: "{{ jenkins_user_name }}"
#  tasks:
#    - name: Add master publickey into authorized_key
#      authorized_key:
#        user: "{{ jenkins_user_name }}"
#        state: present
#        key: "{{ hostvars['jenkins-master-01']['ssh_key_info'] }}"
#    - name: Create agent_dir
#      become_user: root
#      file:
#        path: "{{ jenkins_agent_dir }}"
#        state: directory
#        owner: "{{ jenkins_user_name }}"
#        group: "{{ jenkins_user_group }}"
    - name: Install some required
      become_user: root
      apt:
        name:
          - git
          - python3
          - pip
          - docker.io
        state: present
    - name: Update pip
      become_user: root
      pip:
        executable: pip3
        name: pip
        extra_args: --upgrade
#    - name: Install Ansible
#      become_user: root
#      pip:
#        executable: pip3
#        name:
#          - selinux
#          - ansible<3.0
#        state: present
    - name: Add local to PATH
      lineinfile:
        dest: ~/.bashrc
        regexp: export PATH=$PATH:/home/jenkins/.local/bin
        line: export PATH=$PATH:/home/jenkins/.local/bin
    - name: Create docker group
      become_user: root
      group:
        name: docker
        state: present
    - name: Add jenkinsuser to dockergroup
      become_user: root
      user:
        name: "{{ jenkins_user_name }}"
        groups: docker
    - name: Restart docker
      become_user: root
      systemd:
        name: docker
        state: restarted
        enabled: true
#    - name: Install agent.jar
#      get_url:
#        url: "http://{{ hostvars['jenkins-master-01']['ansible_host'] }}:8080/jnlpJars/agent.jar"
#        dest: "{{ jenkins_agent_dir }}"
#      register: install_agent
#      until: install_agent is succeeded
#      retries: 10
#      timeout: 10

