apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-multitool-deployment
  labels:
    app: busybox-multitool-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  busybox-multitool
  template:
    metadata:
      labels:
        app:  busybox-multitool
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        volumeMounts:
          - name: vol
            mountPath: /input
      - name: busybox
        image: busybox
        command: ['sh', '-c', 'while true; do echo "Learning again!" >> /output/Way_to_devOps.txt; sleep 5; done']
        volumeMounts:
          - name: vol
            mountPath: /output
      volumes:
      - name: vol
        hostPath:
          path: /var/data


---

apiVersion: v1
kind: Service
metadata:
  name: busybox-multitool-svc
spec:
  selector:
    app: busybox-multitool
  ports:
    - name: web
      port: 80