apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiremock-deployment
  labels:
    app: wiremock
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  wiremock
  template:
    metadata:
      labels:
        app:  wiremock
    spec:
      containers:
      - name: wiremock
        image: wiremock:2.33.1
        ports:
          - containerPort: 8080
            name: web
            protocol: TCP