apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-multitool-deployment
  labels:
    app: nginx-multitool
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  nginx-multitool
  template:
    metadata:
      labels:
        app:  nginx-multitool
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds:  10
          periodSeconds:  5
        ports:
          - containerPort: 8080
            name: web
            protocol: TCP
      - name: multitool
        image: wbitt/network-multitool
        env:
          - name: HTTP_PORT
            value:  "81"
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds:  10
          periodSeconds:  5
        ports:
          - containerPort: 8081
            name: web
            protocol: TCP