apiVersion: v1
kind: Pod
metadata:
  name: multitool
  labels:
    app: multitool
spec:
  containers:
      - name: multitool
        image: wbitt/network-multitool
        livenessProbe:
          httpGet:
            path: /
            port: 8082
        env:
          - name: HTTP_PORT
            value: "82"
        ports:
          - containerPort: 8082
            name: web
            protocol: TCP
