apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-multitool-deployment
  namespace: app-upd
  labels:
    app: nginx-multitool
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 3
  selector:
    matchLabels:
      app:  nginx-multitool
  template:
    metadata:
      labels:
        app:  nginx-multitool
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.0
        ports:
          - containerPort: 8080
            name: web
            protocol: TCP
      - name: multitool
        image: wbitt/network-multitool
        env:
          - name: HTTP_PORT
            value:  "81"
        ports:
          - containerPort: 8081
            name: web
            protocol: TCP